name: Python CI + Docker Build & Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # 1. Python CI Job
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  # 2. Docker Build and Push Job
  docker:
    runs-on: ubuntu-latest
    needs: test  # Only run Docker build if tests pass

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set image tag (date-based)
      id: vars
      run: echo "TAG=$(date +'%d-%m-%Y')" >> "$GITHUB_OUTPUT"

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/python-ci-cd-demo:${{ steps.vars.outputs.TAG }} .

    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/python-ci-cd-demo:${{ steps.vars.outputs.TAG }}

    - name: (Optional) Tag and push latest
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/python-ci-cd-demo:${{ steps.vars.outputs.TAG }} ${{ secrets.DOCKER_USERNAME }}/python-ci-cd-demo:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/python-ci-cd-demo:latest
